### ISSUE TITLE
Seems to break the Vue router

### ISSUE THREAD

**Issue by Theorian** [antoniandre/splitpanes#1]
cannot seem to nest the router-view in it

**Comment by antoniandre** [comment]
Hi @Theorian,

I tried to place a router view inside splitpanes, even in nested splitpanes like so:
```
<splitpanes class="default-theme" horizontal style="height: 400px">
  <span>1</span>
  <splitpanes>
    <span>2</span>
    <router-view/>
  <span>3</span>
  </splitpanes>
</splitpanes>
```

And I have no problem rendering my component inside.
Please share your code so we can explore what goes wrong.

**Comment by antoniandre** [comment]
Closed for inactivity.

**Comment by bhoriuchi** [comment]
I am having this issue, see codepen https://codepen.io/bhoriuchi/pen/NWKrNbb

The checkbox enables/disables panes.

Example to reproduce
1. Select Child1 - right pane does not update
2. Uncheck Use Panes - Child1 component is displayed
3. select Use Panes - child one is still displayed
4. Select child 2 - Child1 still displayed
