### ISSUE TITLE
Unable to use v-if/else inside the splitpane.

### ISSUE THREAD

**Issue by rajashekarappala** [antoniandre/splitpanes#10]
Hi @antoniandre,
I need to render the content inside the pane based on the condition.
In the below example I can call the toggle function of the parent but can't use the updated value of `show`.
https://codepen.io/anon/pen/QzBREL

Appreciate the help.

**Comment by antoniandre** [comment]
Hi @rajashekarappala,

You have to use the option watch-slots on splitpanes tag to do this https://codepen.io/antoniandre/pen/dwqzmO,

There is still an ongoing limitation to watch-slots option discussed here https://github.com/antoniandre/splitpanes/issues/7.

**Comment by rajashekarappala** [comment]
Thank you so much @antoniandre, It works
