### ISSUE TITLE
forEach is a not a function

### ISSUE THREAD

**Issue by amir20** [antoniandre/splitpanes#102]
I am testing `next` branch with vuejs. 

I am getting the following error. 

```
Uncaught TypeError: this.container.children.forEach is not a function
    at Proxy.checkSplitpanesNodes (splitpanes.vue:307)
    at Proxy.mounted (splitpanes.vue:675)
    at callWithErrorHandling (runtime-dom.esm-bundler-22e9c19c.js:1215)
    at callWithAsyncErrorHandling (runtime-dom.esm-bundler-22e9c19c.js:1224)
    at Array.hook.__weh.hook.__weh (runtime-dom.esm-bundler-22e9c19c.js:3267)
    at flushPostFlushCbs (runtime-dom.esm-bundler-22e9c19c.js:1343)
    at render (runtime-dom.esm-bundler-22e9c19c.js:5789)
    at mount (runtime-dom.esm-bundler-22e9c19c.js:4175)
    at Object.app.mount (runtime-dom.esm-bundler-22e9c19c.js:8401)
    at main.js:52
```

I believe it is this line

```
checkSplitpanesNodes () {
      this.container.children.forEach(child => {...
```

There is no `forEach` on `HTMLCollection`. I believe you want something like `[...this.container.children].forEach`. 

Maybe this was getting fixed with webpack?

**Comment by antoniandre** [comment]
Hi @amir20, thanks for reporting.
You're right I did not pay attention writing that line whereas I traversed the same HTML collection correctly elsewhere in the code. What is curious is that it's never got picked up until now, even on my machine.

Anyway please give a try at version 3.0.1 and let me know. 
This demo seems to work fine: https://codepen.io/antoniandre/pen/LYNKGWV

**Comment by amir20** [comment]
Thanks! I am traveling for a few days. Will try it and let you know. 

Sent via my iPhone

**Comment by amir20** [comment]
This looks to be fixed now. I did noticed that you are relying on webpack's extension resolver and this breaks vite and rollup. So I am going to send you a pr.

**Comment by amir20** [comment]
Pull request sent. Also as mentioned in another issue, I am a big fan of webpack too. But recently I have been needing to do bundling for more optimized outputs. Cheers.

**Comment by antoniandre** [comment]
Hi @amir20, I merged in the PR and released version 3.0.2. 
Please test if it works with your setup and let me know.

**Comment by amir20** [comment]
Thanks! I had done `npm link` so I know it works. 

I am having a different issue right now. Probably not related to you. Looks vite's optimization breaks some things. 

Will update more when I find out what's going on.

**Comment by antoniandre** [comment]
Hi @amir20, have you found out?
Please close the issue if solved. :)

**Comment by amir20** [comment]
Let’s close this issue. I don’t think it’s related for now.
