### ISSUE TITLE
Vite incompatable

### ISSUE THREAD

**Issue by lchrennew** [antoniandre/splitpanes#105]
```
Uncaught SyntaxError: The requested module '/@modules/splitpanes/dist/splitpanes.common.js' does not provide an export named 'Pane'
```
Should package module version.

**Comment by antoniandre** [comment]
Hi @lchrennew, Splitpanes does not provide an ESM module as Webpack can't do that yet.
You have to generate it yourself: https://github.com/antoniandre/splitpanes/issues/97

Hope it helps.
Please reopen with more details if the above link does not help you.
