### ISSUE TITLE
dbl-click-splitter setting doesn't deactivate touch dbl click

### ISSUE THREAD

**Issue by MentalGear** [antoniandre/splitpanes#106]
Thank you for this fantastic, easy to use and powerful plugin.

I noticed that when setting dbl-click-splitter to false, the double click mouse events doesn't expand pane anymore, but on touch devices, it still does.

**Comment by MentalGear** [comment]
After a quick source review, I think the issue lies here
https://github.com/antoniandre/splitpanes/blob/3d3bcf144496a923c25bd098fa04bde2ec92c995/src/components/splitpanes/splitpanes.vue#L109

**Comment by antoniandre** [comment]
Hi @MentalGear,
Thanks for your feedback and for reporting.
This is indeed a bug, well spotted! 
I fixed this in version 2.3.5, hope it helps.
