### ISSUE TITLE
Splitpanes may lead memory leak

### ISSUE THREAD

**Issue by Alecyrus** [antoniandre/splitpanes#11]
When I use splitpanes in my component, if I switch the component by changing the routes page frequently. I found the number of splitpanes component instance could increase with the routes changing. Once I comment all splitpanes code, the memory usage falls down. Recently I realize the memory management is very important because the memory leak of my APP, so i start to assess the potential memory leak risk of every 3-rd party component I used.

The following is timeline analysis. With the splitpanes component & Without splitpanes component
![image](https://user-images.githubusercontent.com/13865581/50946421-1fc2e780-14d4-11e9-8d4c-ce06034a0950.png)

![image](https://user-images.githubusercontent.com/13865581/50946525-ba232b00-14d4-11e9-94ce-7bde124536aa.png)

**Comment by Alecyrus** [comment]
I probably found the reason.
```javascript
    bindEvents () {
      const hasTouch = 'ontouchstart' in window
      // Passive: false to prevent scrolling while touch dragging.
      document.addEventListener(hasTouch ? 'touchmove' : 'mousemove', this.onMouseMove, { passive: false })
      document.addEventListener(hasTouch ? 'touchend' : 'mouseup', this.onMouseUp)
    }
```
It seems like that you didn't unbind the event listener when the component is destroyed.

**Comment by Alecyrus** [comment]
Solved.
![image](https://user-images.githubusercontent.com/13865581/50946954-f0fa4080-14d6-11e9-8d16-0d69390eeb0d.png)
wait my PR

**Comment by Alecyrus** [comment]
#12

**Comment by antoniandre** [comment]
Hi @Alecyrus,

Thanks for your investigation and PR, I will merge it in shortly.
