### ISSUE TITLE
Feature request: Built-in localStorage for pane sizes

### ISSUE THREAD

**Issue by d95sld95** [antoniandre/splitpanes#116]
It would be great to have built-in support for localStorage so that the size of each pane is remembered once you come back to the page. Idea copied from PrimeVue.js

Stateful

> Splitters can be configured as stateful so that when the user visits the page again, the adjusts sizes can be restored. Define a stateKey to enable this feature. Default location of the state is session storage and other option is the local storage which can be configured using the stateStorage property.

**Comment by posva** [comment]
I know this is old but FYI, I don't think this should be added to the library. It can be achieved with a few lines of code: [see this Vitest UI PR](https://github.com/vitest-dev/vitest/pull/5166)

**Comment by antoniandre** [comment]
Yes, I agree it can become a problem for other use cases and should be externalized.
thanks for chiming in @posva! 
and I’m glad to see my lib is in use in vitest UI 🎉
I’ll spend some time to improve a few things soon
