### ISSUE TITLE
Vue3 Splitpanes with Element+: failed to resolve component pane/splitpanes

### ISSUE THREAD

**Issue by DigitTwin** [antoniandre/splitpanes#126]
With  the attached HTML file the Element+ button is displayed but the panes are not.
Would expect that Splitpanes can be used with Vue3 as in the example (similarly to an ElButten).

(Warning in console:)
[Vue warn]: A plugin must either be a function or an object with an "install" function.
[Vue warn]: Failed to resolve component: pane at <App>
[Vue warn]: Failed to resolve component: splitpanes  at <App>

[index3.html.txt](https://github.com/antoniandre/splitpanes/files/6327123/index3.html.txt)

**Comment by DigitTwin** [comment]
When using splitpanes within .vue files in a vite project it works.
So, this (importing via <script> tag) does no longer matter.

**Comment by sanketsatarkar** [comment]
Failed to resolve component: splitpanes
Failed to resolve component: pane
"vue": "3.2.47",
"splitpanes": "^3.1.5",
