### ISSUE TITLE
watch-slots option causes a complete refresh [Duplicate]

### ISSUE THREAD

**Issue by m-mohr** [antoniandre/splitpanes#13]
I have a component that works wonderfully without Splitpanes. Unfortunately, if I wrap these with the SplitPanes component, the props won't be passed any longer. The splitter itself works nicely, but all the components inside the panels don't work well any longer. What's happening there and how can it be fixed? Thanks!
```
<Splitpanes class="default-theme">
  <div id="ide">
    <BackendPanel :connection="connection" />
  </div>
  <div id="viewer">
    <MapViewer :connection="connection" />
    <ImageViewer :connection="connection" />
  </div>
</Splitpanes>
```

**Comment by tandrew** [comment]
@m-mohr: Sounds similar to a previous issue with reactive properties [#3](https://github.com/antoniandre/splitpanes/issues/3).
I am also having reactivity issues [#7](https://github.com/antoniandre/splitpanes/issues/7) with this control and have held back from deploying it so far.

Let's hope @antoniandre can address these issues soon.

**Comment by antoniandre** [comment]
Hi guys, 
Thanks for your feedbacks, I know this is a big limitation, I will work on that shortly.
Please follow up in #14.
