### ISSUE TITLE
watch-slots option causes a complete refresh

### ISSUE THREAD

**Issue by jlpospisil** [antoniandre/splitpanes#14]
If watchSlots is true, any change in the slot(s) causes a complete refresh.  If I manually resize the panes, I would like them to stay where I have put them even if the data in a slot changes.

**Comment by antoniandre** [comment]
Hi @jlpospisil, 
Thanks for your feedback, I understand the issue and will work on that soon.
Original issue: #7.

**Comment by antoniandre** [comment]
Hi @jlpospisil,

I have released version 1.11.1 that should fix this.
Let me know if anything still doesn't behave as expected.

**Comment by jlpospisil** [comment]
@antoniandre Thanks!  Looks good.
