### ISSUE TITLE
Gives Errors with Vue3 (Vue latest version) CDN

### ISSUE THREAD

**Issue by FelixFreelancer** [antoniandre/splitpanes#140]
I need to use this package with Vue 3.
This is my template/script.

`<Html>`

    <head>
        <title>
            Test (Vue 3)
        </title>`
        <script src="https://unpkg.com/vue@next"></script>
        <script src="https://unpkg.com/splitpanes"></script>
        <link href="https://unpkg.com/splitpanes/dist/splitpanes.css" rel="stylesheet">
    </head>
    <body>
        <div id="app">
            <splitpanes class="default-theme" horizontal style="height: 400px">
                <pane min-size="20" max-size="70">
                    <span>1</span>
                </pane>
                <pane>
                    <span>2</span>
                </pane>
                <pane max-size="70">
                    <span>3</span>
                </pane>
            </splitpanes>
        </div>
        
    </body>
    <script>
        const{ Splitpanes, Pane } = splitpanes

        const app = Vue.createApp({
            components: {
                'splitpanes': Splitpanes,
                'pane': Pane
            },
            data() {
                return {
                    title: 'Test'
                }
            }
        }).mount("#app");

     </script>

`</html>`

It gives these errors.
![image](https://user-images.githubusercontent.com/40544276/123898765-f0b6bf80-d933-11eb-9399-f271c3c9dd22.png)

Please let me know how to fix this issue.

**Comment by antoniandre** [comment]
Hi @FelixFreelancer, like for Vue, in Vue 3 you should use `splitpanes@next`.
Please reopen if not solved :)
