### ISSUE TITLE
Hide splitter

### ISSUE THREAD

**Issue by edbotdev** [antoniandre/splitpanes#158]
I have 2 panes with vertical splitter. I have a toggle button to expand / restore first pane to full / original width. It does this by setting the splitpanes 'size' prop. Works well. However I need to hide the splitter in the expanded state and show it in the restored state. Is there a way I can do this? Thanks.

**Comment by antoniandre** [comment]
Hi @edbotdev, I would do this via CSS.
Please share a reproduction link so I can help you.
Please reopen if not solved.
