### ISSUE TITLE
Jittery jumpy separator on drag

### ISSUE THREAD

**Issue by tandrew** [antoniandre/splitpanes#17]
Hi @antoniandre,
Opening a new issue here based on my previous observations.

When using a reactive field, which changes upon resize changes, I am getting a lot of jitter when dragging a separator.

Try dragging the horizontal separator in this [CodePen](https://codepen.io/tandrew-the-bold/pen/ZVXvMP?editors=1111) and you will see what I mean.

Might be something I am doing wrong here. In that case please advise.

![feb-07-2019 18-13-13](https://user-images.githubusercontent.com/8017453/52429467-696b1600-2b04-11e9-8bc0-10e237659f1c.gif)

_Originally posted by @tandrew in https://github.com/antoniandre/splitpanes/issues/7#issuecomment-461517110_

**Comment by antoniandre** [comment]
Thanks @tandrew for this reproduction link. I suspect reapplying width or height on changed slot is not fast enough while dragging... I'll have a look into the code to see what I can do.

**Comment by antoniandre** [comment]
Hi @tandrew, this is now solved... Yay!
https://codepen.io/antoniandre/pen/dyyoNeY?editors=1111

This issue was fixed in the V2. (ref. #60, thanks to @jonathan-roy)

**Comment by antoniandre** [comment]
PS: Please check the release notes and how to install again. https://antoniandre.github.io/splitpanes/#release-notes

**Comment by antoniandre** [comment]
Closing the issue as fixed now.
