### ISSUE TITLE
How implement fixed one column?

### ISSUE THREAD

**Issue by Penggeor** [antoniandre/splitpanes#172]
I have three columns but the middle column needed to be fixed, how to implement it? 
Need u help!

**Comment by antoniandre** [comment]
Not implemented yet: #84

**Comment by everydaysoftware** [comment]
Hi Antoni, would you implement it when I pay you for it? Contact me! pls.

**Comment by antoniandre** [comment]
Hi @everydaysoftware , thanks for the offer. I can't say I have much spare time at the moment but let's get in touch and see.
You can find my email in the package.json of this library, or you can give me your email and I'll reach you.
Cheers
