### ISSUE TITLE
`module` and `exports`  fields in package.json pointing to non-existant file `splitpanes.es.js`

### ISSUE THREAD

**Issue by EosFoundry** [antoniandre/splitpanes#179]
Specifically `./dist/splitpanes.es.js` does not exist as referenced below:

```json
  "module": "./dist/splitpanes.es.js",
  "exports": {
    ".": {
      "import": "./dist/splitpanes.es.js",
    },
  },
```
This is the contents of the package as pulled from npm:

![image](https://user-images.githubusercontent.com/99506313/197944389-ad3705db-2fad-4759-86e2-4b832b73d404.png)

Should it be pointing to `./dist/splitpanes.mjs` instead?

**Comment by desislavsd** [comment]
Yes, I faced that issue too. It breaks my vite setup, but when update package.json to .mjs it works fine. 

Here is the [PullRequest](https://github.com/antoniandre/splitpanes/pull/180)

**Comment by antoniandre** [comment]
This should now be fixed in the latest package. 3.1.4
