### ISSUE TITLE
Can't use <router-view/> inside a pane with watchSlots option 

### ISSUE THREAD

**Issue by enf644** [antoniandre/splitpanes#18]
```
<template>
  <splitpanes watch-slots>
    <div>
      <TheUsersManagerDrawer></TheUsersManagerDrawer>
    </div>
    <div>
      <router-view/>
    </div>
  </splitpanes>
</template>
```

I get error 
> TypeError: Converting circular structure to JSON

And without watch-slots, **router-view** is not updated after route changed.

**Comment by antoniandre** [comment]
Hi @enf644, version 1.11.2 should fix this.

**Comment by antoniandre** [comment]
Closed for inactivity. Please reopen if issue is still not solved.
