### ISSUE TITLE
Save current state panes

### ISSUE THREAD

**Issue by maxisoft-git** [antoniandre/splitpanes#2]
How can I save the current state of the panels, and after updating the page, restore the previously set sizes of the panels?

**Comment by antoniandre** [comment]
Hi @maxisoft-git, 
I will emit events in the next release coming soon. So that you can listen for these events and trigger actions outside of splitpanes.

**Comment by maxisoft-git** [comment]
I will look forward to

**Comment by antoniandre** [comment]
Hi @maxisoft-git,

I released a new version and you can now get the dimensions of the panes each time you resize them through the resize event [antoniandre.github.io/splitpanes/#emitted-events](https://antoniandre.github.io/splitpanes/#emitted-events).

In addition to that I added a default width or height option on the panes for when you first load. So you will need that as well when you reload the page [antoniandre.github.io/splitpanes/#default-pane-width](https://antoniandre.github.io/splitpanes/#default-pane-width).

Hope it helps!

**Comment by antoniandre** [comment]
Hi @maxisoft-git, 
let me know if you need further assistance with that.

**Comment by antoniandre** [comment]
The feature request is now implemented.
Closed for inactivity.
You can reopen if you need more help on that!
