### ISSUE TITLE
Is this library dead?

### ISSUE THREAD

**Issue by davestewart** [antoniandre/splitpanes#206]
I know running OSS projects is hard (I have a few!) but no real activity by the author since Oct 2022:

- [last meaningful comment](https://github.com/antoniandre/splitpanes/issues?q=is%3Aissue+commenter%3Aantoniandre)
- [last merged PR](https://github.com/antoniandre/splitpanes/pulls?q=is%3Apr+is%3Aclosed)

It's a shame, as it's a nice lib.

But I need changes so I've since forked and modified myself.

**Comment by rexhent** [comment]
I made a fork if you would like to merge your changes into mine, I've also created an npm package at splitpanes4

https://github.com/rexhent/splitpanes

**Comment by antoniandre** [comment]
Hello guys,
I've been willing to dedicate more time but indeed I've been busy on other OSS projects 🤷 
I plan to work on refreshing the lib this summer though, moving to composition API and adding a couple features. 💪 
Thanks for support!

**Comment by rexhent** [comment]
> Hello guys, I've been willing to dedicate more time but indeed I've been busy on other OSS projects 🤷 I plan to work on refreshing the lib this summer though, moving to composition API and adding a couple features. 💪 Thanks for support!

i've already done a bit of moving to composition api, and can send over some PR's when your ready.

**Comment by antoniandre** [comment]
Hey folks, just a heads up that I've been actively working on Splitpanes. :)
I did a few changes on main already, but also moved some more ongoing refactoring in the refactor-resizing branch.
Once I have nicely improved / fixed / cleaned up on the core features, I'll take on some new features like the fixed panes and pixel-base resizing.
