### ISSUE TITLE
Cannot do this. Double-click the splitter to maximize the next pane.

### ISSUE THREAD

**Issue by lost-xming** [antoniandre/splitpanes#22]
你好，我们正在积极使用着这个插件，但是使用过程中需要禁止掉双击拆分器事件，

在api 文档中并没有发现双击事件以及相关说明

**Comment by antoniandre** [comment]
??

please write in english.

**Comment by lost-xming** [comment]
Cannot do this. Double-click the splitter to maximize the next pane.

Hello, we are actively using this plugin, but we need to disable the double click splitter event during use.

No double-click events and related instructions were found in the api documentation

**Comment by antoniandre** [comment]
Hi @lost-xming, 

This is now an option in version 1.12.0.
Add this attribute: `:dbl-click-splitter="false"`

Please refer to this example: https://antoniandre.github.io/splitpanes/#horizontal-layout

Hope this helps.

**Comment by antoniandre** [comment]
Closed for inactivity.
