### ISSUE TITLE
Cannot resize pane in Firefox + Touch Screen

### ISSUE THREAD

**Issue by Narretz** [antoniandre/splitpanes#23]
I have a Lenovo Yoga 460 (Windows) that has a touch screen. When I'm in Firefox, none of the resize functions work - not drag with mouse or touch, no double click. It does work in Edge and Chrome.
One key difference I found is that Firefox has window.ontouchstart, but Chrome and Edge do not.

**Comment by antoniandre** [comment]
Hi @Narretz,
I was foreseeing this would happen. 😅
I detect `hasTouch = 'ontouchstart' in window` on load then add the the event listener accordingly:

```js
document.addEventListener(hasTouch ? 'touchmove' : 'mousemove', this.onMouseMove, { passive: false })
      document.addEventListener(hasTouch ? 'touchend' : 'mouseup', this.onMouseUp)

```

I'm gonna add all the event listeners to see if this can help and will let you have another try.

**Comment by antoniandre** [comment]
Hi @Narretz,
I have published version 1.12.1.
It should fix the double tap on splitter, and hopefully the dragging ability on firefox. Please test and let me know.

**Comment by Narretz** [comment]
Hi, it works now in Firefox with mouse and even with touch. Thanks!

**Comment by antoniandre** [comment]
Awesome 👌
