### ISSUE TITLE
Can't use watchSlots when pane contains a functional component (via vue-loader)

### ISSUE THREAD

**Issue by Narretz** [antoniandre/splitpanes#24]
splitpanes throws an error when I have a functional template:

```
[Vue warn]: Error in render: "TypeError: Converting circular structure to JSON"

found in

---> <Splitpanes> at splitpanes.vue
       <MyComp> at src/components/MyComp.vue
 
 TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Proxy.render (webpack:///./node_modules/splitpanes/dist/splitpanes.common.js?:447)
    at VueComponent.Vue._render (webpack:///./node_modules/vue/dist/vue.runtime.esm.js?:3529)
    at VueComponent.updateComponent (webpack:///./node_modules/vue/dist/vue.runtime.esm.js?:4031)
```

```
<template functional>
  <div>
  </div>
</template>
```

That is compiled with vue-loader.
It does not happen when I have a functional component with render function.

**Comment by antoniandre** [comment]
Hi @Narretz,
Can you please provide more code as I can't reproduce? A codepen or codesandbox would be most helpful.

**Comment by ChuckFields** [comment]
I'm experiencing a similar issue. I've reproduced it here:
[https://codesandbox.io/s/xpp9k24o34](https://codesandbox.io/s/xpp9k24o34)

**Comment by antoniandre** [comment]
Thank you for your feedbacks.
Please continue discussion and watch changes in #47.
