### ISSUE TITLE
Pane snaps back when class is changed inside it on @resized event

### ISSUE THREAD

**Issue by MagicKriss** [antoniandre/splitpanes#25]
Hi, @antoniandre 
I am having a resize problem similar to the one described in here #7 
What I have found is that triggering class change on `@resized` (with '**d**') snaps the pane size back to original state. 
I have created a code pen to display the problem
`@resized` snaps back:   https://codepen.io/anon/pen/xBdJGW

**Comment by antoniandre** [comment]
Hi @MagicKriss,
I have modified your codepen slightly: https://codepen.io/antoniandre/pen/wOeRKo?editors=1010,
then realised yours seems to be working fine too.
The only thing that I think have changed is the version of splitpanes in use in codepen, now it is the latest, but it could have been cached to a previous version from unpkg at the time you had the bug.
Let me know if it is solved now.

**Comment by MagicKriss** [comment]
Thanks, I guess I had installed some previous version with yarn add.
Updating solved this problem, thanks!
