### ISSUE TITLE
Vue splitpanes resizing

### ISSUE THREAD

**Issue by nayils** [antoniandre/splitpanes#30]
Hi! I use splitpanes. But it does not have the ability to resize programmatically, just set the default value. Is it possible to do something so that splitpanes can resize by programmatically?

For example, so that when I click on a button, I can hide the left panel, or change its size.

**Comment by antoniandre** [comment]
Hi @nayils this is now possible in version 1.14.1. https://antoniandre.github.io/splitpanes/#programmatic-resizing

**Comment by antoniandre** [comment]
Closing the issue as resolved. Please reopen if not fixed.
