### ISSUE TITLE
Floating horizontal panes when in mobile view

### ISSUE THREAD

**Issue by hnviradiya** [antoniandre/splitpanes#32]
Is there any configuration possibility that, when splitter is in mobile view horizontal panes can be converted to vertical.

Because this way we can add responsiveness in different way.

So that only one pane per row.

E.g.
In desktop view
1-2-3
Becomes following in mobile view
1
2
3

But only if it is configured by some configuration option so that people who don't want to do this can keep as it is.

Reason is it becomes very small in mobile view when horizontal panes are there.

**Comment by vanhumbeecka** [comment]
I'm looking at the same problem. I want 2 panes, but depending on the parent container, the splitter should be vertical or horizontal.

In short:
- when 'landscape' layout --> default to "Vertical splitter"
- when in 'portrait layout --> Change responsively to "Horizontal splitter"

Is there an easy solution to this? Would be very nice to have.

**Comment by hnviradiya** [comment]
awesome. can be managed. closing. thanks.
