### ISSUE TITLE
Feature request: Event dynamic size

### ISSUE THREAD

**Issue by nayils** [antoniandre/splitpanes#34]
You have added cool functionality for the dynamic size of the panels. When changing the size, the panels smoothly change their size. It is beautiful. But could you add an event when the tween has ended? That is, when the panel has already taken the value of a given size?

**Comment by antoniandre** [comment]
Hi @nayils, Sorry to take so long to answer.
I don't think I should put a callback after the animation ends, the default transition is set to 0.2s but people might override this transition or don't include the styles.

The callback would then fire at the wrong time.
So I think if you have this need, you can either remove this transition, 
```css
.splitpanes__pane {transition: none;}
```

or set a timeout of the same amount from the `resized` emitted event.

Hope it helps, sorry for the wait again.
