### ISSUE TITLE
cascaded splitpanes with a vuetify v-tabs/v-tab in inner splitpanes breaks reactivity

### ISSUE THREAD

**Issue by mrQ000** [antoniandre/splitpanes#35]
seems to be some incompatibility with vuetify.
i prepared a minimum setup to explain and reproduce this issue:

https://codepen.io/mrQ_/pen/KYNVwa

**Comment by antoniandre** [comment]
Thank you for your feedbacks.
Please continue discussion and watch changes in #47.
