### ISSUE TITLE
documentation - css selector should be more precise

### ISSUE THREAD

**Issue by mrQ000** [antoniandre/splitpanes#36]
original:
```
.splitpanes__pane span {
  font-family: Helvetica, Arial, sans-serif;
  color: #fff;
  font-size: 5em;
  opacity: 0.6;
}
```
above code will select any span at any level below .splitpanes__pane,
but the selector should apply to immediate childs of splitpanes__pane only.

suggested modification:
```
.splitpanes__pane > span {
    ...
}
```

**Comment by antoniandre** [comment]
This does not matter at all. It is only an example of how to style. It is intended to be a simple example that anybody can understand. To be modified according to context.
