### ISSUE TITLE
Programmatic resizing doesn't update model

### ISSUE THREAD

**Issue by pprzetacznik** [antoniandre/splitpanes#39]
@antoniandre
I found two problems with splitpanes. I've published my code here: https://codesandbox.io/s/o4247q0jjz

1. I need to embedd my code inside `<no-ssr>` tag. If not, I see `window is not defined
` error. You can see this error by clicking 'Check how it works without no-ssr' link on the index page.
![image](https://user-images.githubusercontent.com/2965785/56755043-db134180-678e-11e9-8b71-187fef1eb528.png)

2. When I embedd splitpanes inside `<no-ssr>` tag, I can see that `<input type="range">` doesn't work properly. I'm not able to manipulate `paneSize` by using it. Also when I change slidepanes' size, sliders and labels inside `<span>` tag don't move. However, they move when I use buttons with `@click` functions.

Note: I'm newbie in js world, so maybe this is something really basic, however I'm fighting with this for a long time and I'm out of ideas right now. I would be grateful for any comments.

**Comment by pprzetacznik** [comment]
I've added PR with `(typeof window !== 'undefined')` condition in splitpanes component so the first point is fixed and doesn't require `<no-ssr>` tags anymore but the second problem still occurs.

https://github.com/antoniandre/splitpanes/pull/40

**Comment by antoniandre** [comment]
Hi @pprzetacznik,
Thank you for your reproduction link, it makes things easier.
You should use the `no-ssr` tag if you use Nuxt, this library has no purpose or benefit from running in server-side.
This is only for client side. Therefore checking for window is irrelevant.

I forked your codesandbox and modified it to bind the slider to the paneSize value.
https://codesandbox.io/s/1467k3z0jq
Basically you just need to call this function on input event.

```js
  methods: {
    updatePaneSize(e) {
      this.paneSize = e.target.value;
    }
  }
```

Let me know if that's what you were looking for or still not solved.

**Comment by pprzetacznik** [comment]
Thanks @antoniandre!

Your solution is really cool. I've also added to the example the attribute `@resize="updatePaneSize2"` and method:
```
  methods: {
    ...
    updatePaneSize2(e) {
      this.paneSize = Math.round(e[0]["width"]);
    }
  }
```
to have the slider sliding while resizing the pane.
