### ISSUE TITLE
Splitpanes prevent inside canvas to be updated / redrawn

### ISSUE THREAD

**Issue by onekiloparsec** [antoniandre/splitpanes#42]
This is by far the best splitpanes lib in town! Unfortunately, my middle pane contains 2 canvas where I draw a lot of things. But they seem to never redraw when put inside splitpanes.

I thought it was the same problem as the one describe in #21 But even when adding `watch-slots` as attribute of `splitpanes`, my canvas don't get updated. Any idea ? Thanks a lot!

**Comment by alexanderVu** [comment]
Have the same problem. The component is not useable!

**Comment by antoniandre** [comment]
@onekiloparsec, 
Thank you for your feedbacks.
Please continue discussion and watch changes in #47.
Unfortunately the component needs to be rebuilt to fix this.
