### ISSUE TITLE
Resetting size of panes after data change

### ISSUE THREAD

**Issue by pprzetacznik** [antoniandre/splitpanes#43]
I've seen similar bugs in the history of issues but this may be some unknown edge case not reported yet. Bug shows only when attribute `watch-slots` is used.

Example: https://codesandbox.io/s/54xm1m42wn
1. Double click on splitter so 2nd pane is at full size (as shown at the picture)
![image](https://user-images.githubusercontent.com/2965785/57572726-0056af80-741f-11e9-9b25-6c040e9ca0a8.png)
2. Make change in the `input` (eg. add letter `a` to the input box)
3. Panes are automatically getting back to the previous sizes
![image](https://user-images.githubusercontent.com/2965785/57572752-50357680-741f-11e9-93b0-8a721bc67ae8.png)

Note: If I manually set sizes of panes, eg. 27:73. Then double click on splitter and add text to the input textbox then it gets back to the 27:73 setting, not the default 50:50.

**Comment by pprzetacznik** [comment]
@antoniandre I've noticed that `pane.savedWidth` is set incorrectly after maximizing pane.

**Comment by KezeiZ** [comment]
I am also encountering this issue. Using spitpanes to display multiple SortableJS/Vue.Draggable lists. Upon re-ordering a list with dynamic data (with watch-slots enabled) the pane will resize to the default size.

**Comment by pprzetacznik** [comment]
@KezeiZ probably this change helps afair https://github.com/antoniandre/splitpanes/pull/49/commits/42dc79a7e91ee7978c9080a09bc70dd9a2a4977b

**Comment by xiaolee55** [comment]
Is this question solved?

**Comment by xiaolee55** [comment]
I am troubled by this problem now @pprzetacznik  Help me ,manito !

**Comment by xiaolee55** [comment]
Oh,My God!I have solved this,It turns out that the author did not upload the latest version to NPM

**Comment by Jakob-Maudience** [comment]
Any idea when the version will be bumped and uploaded to npm?

**Comment by xiaolee55** [comment]
@Jakob-Maudience,You have to ask the author,but In fact  the merged Coding will create a new problem---we can't use the  prop "splitpanes-size" to change the size of panes(In addition to the initial value)

**Comment by xiaolee55** [comment]
Instead of waiting the author ,you could change 'paseFloat(paneSizeInDOM)' to 'paseFloat(width)' in the Line 546 in node_module/splitypanes/splitpanes.common.js  by yourself

**Comment by antoniandre** [comment]
> Any idea when the version will be bumped and uploaded to npm?

It is now. version 1.14.5.
If still not fixed, this is still the same issue as #47, please report there.

**Comment by franciscolourenco** [comment]
Having the same issue. With `watch-slots`, `splitpanes-size` is re-applied every times a child is updated. So it doesn't work like initial size, but as the current size.

**Comment by antoniandre** [comment]
Hi @pprzetacznik, @Kezzei, @xiaolee55, @Jakob-Maudience, @franciscolourenco, and everybody,

This issue is related to the known reactivity issue #47, which should now be fixed in the new Version 2 (refer to #60, thanks to @jonathan-roy). 
Please give it a try and let me know if it fixes this issue.

**Comment by antoniandre** [comment]
Hi @pprzetacznik, this is now fixed in V2: https://codesandbox.io/s/example-splitpanes-editor-b2l4y.
Closing the issue now.
