### ISSUE TITLE
Setting splitpanes-size in pixels

### ISSUE THREAD

**Issue by Gnopps** [antoniandre/splitpanes#45]
Great work with this, thank you! 

I'd like to set the default size for a pane with splitpanes-size in pixels, and that the second pane then fills the remaining width in %. Is this possible?

**Comment by antoniandre** [comment]
Hi @Gnopps, this is currently not possible, but I might add it in a future version.
Please watch the changes (and continue the thread if needed) in this issue: #16 
Thanks.

**Comment by Gnopps** [comment]
Thanks for your answer! I didn't write in that other thread as I thought it was only for max/min, not default.
