### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by GLeBaTi** [antoniandre/splitpanes#46]
Hello. How can i use this in my project?
By tutorial i was add this to header:
```
<script src="https://unpkg.com/splitpanes"></script>
<link href="https://unpkg.com/splitpanes/dist/splitpanes.css" rel="stylesheet">
```
And trying using in my code:

```
"use strict"
let AGTest = {
    components: { },
    template: `
<div>
<splitpanes class="default-theme">
  <div v-for="i in 3" :key="i">{{ i }}</div>
</splitpanes>
</div>`
};
Vue.component('ag-test', AGTest)
```

But this not working:

>  Unknown custom element: <splitpanes> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by GLeBaTi** [comment]
https://jsfiddle.net/mrgjLdnh/
this is also not working

**Comment by antoniandre** [comment]
Hi @GLeBaTi,
Simple, you need to mount Vue on a tag first.
Have a look here: https://codepen.io/antoniandre/pen/XybPKP
