### ISSUE TITLE
Watch-slots related issue: not updating vars or JSON circular reference error

### ISSUE THREAD

**Issue by antoniandre** [antoniandre/splitpanes#47]
I am aware of this error and explained it here: #38.
I am considering to do a new version when I will have some time.

Until then if you face this issue, consider it as a limitation or do a pull request to fix it.

Please refrain yourself from creating other issues about this.

**Comment by evgencode** [comment]
The same problem.
Nested component can't watch a props((

**Comment by mudin** [comment]
is there any updates?

**Comment by antoniandre** [comment]
Version 1.14.5 has a different JSON replacer. Please try and let me know.
If it does not fix, please report here too.

Please note I can merge PRs and do small modifications but don't have time for big refactoring like this issue might require.

**Comment by davidlbean** [comment]
Hmmm...I think I'm running into this issue with 1.14.5 -- I've got a dynamically rendered component inside a splitpane and it won't render.  If I move it out of the splitpane, it works fine.  Only adding this to offer a data point -- I'm super grateful for the package, @antoniandre !

**Comment by antoniandre** [comment]
Hi @evgencode, @mudin, @davidlbean, and everybody.
This known issue now have a fix in the new Version 2 (refer to #60, thanks to @jonathan-roy). 

Please give it a try and let me know if it's all good!

**Comment by antoniandre** [comment]
This issue should be fully solved now. I'm closing it, please reopen if not solved.
