### ISSUE TITLE
TypeError: Converting circular structure to JSON on splitpanes

### ISSUE THREAD

**Issue by calebeaires** [antoniandre/splitpanes#5]
I have follow the tutorial to implement it, but Splitpanes has an problem with my code. A simple splitpanes code give this error. 

Code used: 

```vue
<splitpanes style="height: 400px">
  <span splitpanes-min="20">1</span>
  <splitpanes horizontal>
    <span>2</span>
    <span>3</span>
    <span>4</span>
  </splitpanes>
  <span>5</span>
</splitpanes>
```

***console error info: Property or method "toJSON" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.***

```console
[Vue warn]: Error in render: "TypeError: Converting circular structure to JSON"

found in

---> <Splitpanes> at splitpanes.vue
       <ElMain>
         <ElContainer>
           <Insights> at src/views/insights/Insights.vue
             <App> at src/App.vue
               <Root>
```

**Comment by antoniandre** [comment]
Hi @calebeaires, 
This issue is the same as https://github.com/antoniandre/splitpanes/issues/3. 
I just released a patch for this (after you created this issue) please have a look there and let me know!
