### ISSUE TITLE
I dont know what happen

### ISSUE THREAD

**Issue by IDONKN** [antoniandre/splitpanes#50]
rror in render: "TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLDivElement'
    |     property 'swiper' -> object with constructor 'Swiper'
    |     property 'params' -> object with constructor 'Object'
    --- property 'el' closes the circle"

**Comment by IDONKN** [comment]
I am trying to use vue-awesome-swiper in splitpanes but it just got error

**Comment by antoniandre** [comment]
Same as #47
