### ISSUE TITLE
Resize & Resized events return ghost (deleted) panes

### ISSUE THREAD

**Issue by gsqrt2** [antoniandre/splitpanes#52]
Hello @antoniandre and thank you for a great module!

Description:
I have noticed that the resize & resized events return panes in the $event data that might no longer exist. This occurs when panes are reactively removed, because the component internal array panes[] is never sliced down.

Reproduction:
An easy way to reproduce the problem is by adding a "remove pane" button in the [# Adding splitters on the fly](https://antoniandre.github.io/splitpanes/) example and inspecting the panes[] array.

Suggested fix:
A quick fix, although not so elegant, would be to reduce the panes[] array length just after the slot count in render() method. The downside of this fix is that there is no correspondence between the deleted panes and the removed array elements so pane properties might be lost and widths not add up to 100. Still this is an issue that already happens when adding a pane.
A more complete solution might require a bit of refactoring, so the quick fix should be viable.

**Comment by xiaolee55** [comment]
I encounter this problem,too

**Comment by antoniandre** [comment]
Hi @gsqrt2, @xiaolee55, 

This should now be fixed in version 2. 
You can test it here: https://codepen.io/antoniandre/pen/poombWZ, delete a pane, resize panes and inspect the console log.

Let me know if it doesn't help for you.
Cheers.
