### ISSUE TITLE
TypeError: discardProps.contains is not a function

### ISSUE THREAD

**Issue by mudin** [antoniandre/splitpanes#56]
I am having the issue `TypeError: discardProps.contains is not a function`.
Is there something changed?

**Comment by antoniandre** [comment]
My bad. Should be fixed in version 1.14.5

**Comment by mudin** [comment]
@antoniandre thanks I will check it

**Comment by mudin** [comment]
This issue is fixed in version 1.14.5, but `watch-slots` is not working well

**Comment by antoniandre** [comment]
Hi @mudin,
This issue is fixed, closing the issue then.

Regarding watch-slots, this issue is related to the known reactivity issue #47, which should now be fixed in the new Version 2 (refer to #60, thanks to @jonathan-roy). 

Please give it a try and let me know in #47.
Cheers.
