### ISSUE TITLE
Component prevent update router-view

### ISSUE THREAD

**Issue by kalex375** [antoniandre/splitpanes#58]
I am having the issue when I wrap router-view into splitpanes. The nested  is not being updated
Looks like splitpanes prevent events or smth else.
You can find exmaple here in [Codesandbox](https://codesandbox.io/s/vue-template-1jlk2?fontsize=14). If you replace 'splitpanes' tag with div, view is being updated

**Comment by Zosimov** [comment]
Works if you pass the "watch-slots" option to splitpanes: 
`<splitpanes watch-slots ...></splitpanes>`

**Comment by antoniandre** [comment]
@kalex375, just for information, there's now an example in the docs for a router-view inside a pane: https://antoniandre.github.io/splitpanes/#vue-router :)
