### ISSUE TITLE
vue warn : infinite update loop

### ISSUE THREAD

**Issue by chen-ABC** [antoniandre/splitpanes#59]
vue version: 2.5.17
splitpanes version: 1.14.5
code: 
![image](https://user-images.githubusercontent.com/30097790/65739187-fbb53e00-e116-11e9-9d87-a29141302e0f.png)

result:
![image](https://user-images.githubusercontent.com/30097790/65739215-096ac380-e117-11e9-85ce-825f5b33adac.png)

**Comment by antoniandre** [comment]
Hi @chen-ABC, 
I am not sure how it ended up with this infinite loop with this code, but please do install the new V2 that should fix this issue (#60, thanks to @jonathan-roy).

Let me know if this fixes the issue.

**Comment by chen-ABC** [comment]
There was no problem in the vue version 2.6.10

**Comment by chen-ABC** [comment]
install the new V2 (2.6.10+)
