### ISSUE TITLE
Example with the reactive touch zone do not work

### ISSUE THREAD

**Issue by xeroxstar** [antoniandre/splitpanes#63]
Hey,  the reactive touch zone do not work with the given example, i tried EVERYTHING (literally everything) and NOTHING worked, here is an example from the demo page:

```
<splitpanes class="default-theme touch-example" horizontal style="height: 400px">
  <pane>
    <splitpanes :push-other-panes="false">
      <pane>
        <span>1</span>
      </pane>
      <pane>
        <span>2</span>
      </pane>
      <pane>
        <span>3</span>
      </pane>
    </splitpanes>
  </pane>
  <pane>
    <p>In this example the splitters are thin lines but the reactive touch zone is spread to 30 pixels all around!</p>
  </pane>
</splitpanes>
```

and then it i put the css:
```
.splitpanes__splitter {background-color: #ccc;position: relative;}
.splitpanes__splitter:before {
  content: '';
  position: absolute;
  left: 0;
  top: 0;
  transition: opacity 0.4s;
  background-color: rgba(255, 0, 0, 0.3);
  opacity: 0;
  z-index: 1;
}
.splitpanes__splitter:hover:before {opacity: 1;}
.splitpanes--vertical > .splitpanes__splitter:before {left: -30px;right: -30px;height: 100%;}
.splitpanes--horizontal > .splitpanes__splitter:before {top: -30px;bottom: -30px;width: 100%;}
```

Does not work, then i went to node_modules and changed the css file, it will not react to css change, so i have created an [online example](https://codesandbox.io/s/vue-template-5pjct) to prove that the example is broken and not working. By the way it's a nice component!

**Comment by antoniandre** [comment]
Hi @xeroxstar,

The reason why it does not work in your example, but it works in the Codepen example https://codepen.io/antoniandre/pen/XxRZmB and in the documentation, is that you have the CSS class `default-theme` on your splitpanes tag, which overrides the styles you are setting in your example. 

Makes me realise that the code source of this example in the documentation also has this class. This is a mistake I will remove it.

Hope it helps.
