### ISSUE TITLE
It seems that 'splitpanes-size' is now broken

### ISSUE THREAD

**Issue by Blightysoft** [antoniandre/splitpanes#66]
Firstly, excellent work on this.

I think I've found a bug in version 2. The splitpanes-size prop seems to have no effect anymore:

		<splitpanes class='default-theme' vertical>
			<pane splitpanes-size='20'>
				<span>1</span>
			</pane>
			<pane>
				<span>2</span>
			</pane>
		</splitpanes>

Or am I making a mistake somewhere? Thanks.

**Comment by jonathan-roy** [comment]
Hi @Blightysoft,

Since v2.0.0 the `splitpanes-size` attribute is now `size`, since it applies to a `pane` element it would be redundant to prefix it with `splitpanes-`.

```html
<splitpanes class='default-theme' vertical>
    <pane size='20'>
        <span>1</span>
    </pane>
    <pane>
        <span>2</span>
    </pane>
</splitpanes>
```

**Comment by Blightysoft** [comment]
Ah, I foolishly skipped to the bottom and saw the 1.14 release notes. That'll teach me. Thanks!

**Comment by antoniandre** [comment]
> Since v2.0.0 the `splitpanes-size` attribute is now `size`, since it applies to a `pane` element it would be redundant to prefix it with `splitpanes-`.

Thanks for your help @jonathan-roy, and totally agree with that.

Let's close this issue then.

**Comment by antoniandre** [comment]
Thanks for your feedback @Blightysoft, also I have updated the release notes for v2 after reading your comment. 😅 

https://antoniandre.github.io/splitpanes/#release-notes
