### ISSUE TITLE
When I drag the splitter,the pane will get smaller

### ISSUE THREAD

**Issue by xiaolee55** [antoniandre/splitpanes#69]
**To begin, It is two panes,like the follow code(now it is correct)**
![image](https://user-images.githubusercontent.com/37341547/69705699-06994880-1131-11ea-8b9d-1ee2eb91b880.png)
**Then I trigger some  event and It becomes the following(It is correct,too)**
![image](https://user-images.githubusercontent.com/37341547/69705805-3e07f500-1131-11ea-81ea-ae9c4a2f30a4.png)
**then I trigger event to the make it change to the first state(two panes)**
![image](https://user-images.githubusercontent.com/37341547/69705699-06994880-1131-11ea-8b9d-1ee2eb91b880.png)(now it is correct,too)

**Here comes the problem,when I drag the spliter, it becomes as follow:**
![image](https://user-images.githubusercontent.com/37341547/69705882-65f75880-1131-11ea-9c45-dab460cb868d.png)(why the pane1's height and pane2's height add up less than 100)

**then I listen the drag event,find the question(there is two panes,but the data shows three elements, where did the third element come from？**
![image](https://user-images.githubusercontent.com/37341547/69706363-8247c500-1132-11ea-931e-c25a8a3b5d69.png)

@antoniandre

**Comment by antoniandre** [comment]
Interesting @xiaolee55, if you look at this example https://codepen.io/antoniandre/pen/poombWZ, I can't see any problem.

If you can reproduce what you say with the latest splitpanes version, then please share your full code so we can see what's going on.

**Comment by xiaolee55** [comment]
@antoniandre Thanks! I found I am not update the npm so that lead to this question,but I found  a new question, though it  do not influences the layout, as follows
![image](https://user-images.githubusercontent.com/37341547/69812457-214fe800-122b-11ea-803c-aa94daf07986.png)
you can look at the example https://codepen.io/Charklee/pen/oNNKyQd, when changing the status,
it will have error message in the console

**Comment by xiaolee55** [comment]
@antoniandre Thanks! I found I am not update the npm so that lead to this question,but I found a new question, though it do not influences the layout, as follows
image
![image](https://user-images.githubusercontent.com/37341547/69812946-2a8d8480-122c-11ea-9783-48335514ede2.png)

you can look at the example https://codepen.io/Charklee/pen/oNNKyQd, when changing the status,
it will have error message in the console

**Comment by antoniandre** [comment]
Hi @xiaolee55, This is now fixed in version 2.2.0.
https://antoniandre.github.io/splitpanes/#toggle-a-pane-with-v-if

Your same codepen will now work (double check that you hit the right splitpanes version 2.2.0 from the unpkg CDN if it does not)

**Comment by xiaolee55** [comment]
OK！It looks fine now,thanks
