### ISSUE TITLE
Resize problem when reactive field is in pane

### ISSUE THREAD

**Issue by tandrew** [antoniandre/splitpanes#7]
Hi @antoniandre,

I ran into another issue with the component after the latest update (v1.8.1).

See the gif for the problem:

![dec-29-2018 02-22-53](https://user-images.githubusercontent.com/8017453/50531854-c68ca880-0b10-11e9-9a6e-75afa18ad00f.gif)

**Description:**
- I have a blue div in the top right pane (2). It resizes to the size of the top right pane when the horizontal splitter resizes the split between the two right fields (linked to a resize event).
- In the bottom right pane (3) I have a reactive field "divHeight" which should contain the current height of the top right pane.

**Problem:**
The splitter always jumps back to the horizontal center position **if the reactive field in pane 3 is included.**
If the reactive field is excluded, everything works as expected.

I have created both a pen and a repo for this:
Codepen: https://codepen.io/tandrew-the-bold/pen/ZVXvMP
Repo: https://github.com/tandrew/vue-splitpanes-reactive-issue/tree/master/src/components

If you comment out **either or both** line 16 and 49 in the repo everything works as expected.

Please let me know whether I have done something wrong or if there is indeed an issue.

Best
Andrew

**Comment by antoniandre** [comment]
Hi @tandrew,

I understand the problem and it's not something you do wrong.
As Splitpanes now watches all its children for any change, when it occurs everything refreshes which was the last requested feature.

For now I can't think of a way to allow watching outside changes and not refreshing everything.
I need to think about it.

By the way, I don't know if in your app you can set the height of your content in percentage, but that would spare you any calculation.

**Comment by tandrew** [comment]
Hi @antoniandre,

Thanks for following up on this. 

Just to sum up the issue once more and to make sure we are on the same page:
Altering a reactive vue variable within the resize event, where this variable is then used elsewhere (does not have to be within a split pane ... could be anywhere on the page) leads to the aforesaid
 behavior. 

In my instance I need to have the new height (by way of resize) to let another component, which is embedded in one of the panes, know about the changed real-estate size of the pane so that it can redraw itself. For this purpose I am passing the new height on to the embedded vue component via v-bind. This does trigger the described behavior.

I currently know of no feasible workaround for this issue. Therefore I continue to be unable to use this (otherwise wonderful) split pane component of yours.

A solution to this issue would be awesome. 

Thanks!
Andrew

P.S. 
> By the way, I don't know if in your app you can set the height of your content in percentage, but that would spare you any calculation.

Sure, I am aware of this, but thanks for pointing it out.

**Comment by antoniandre** [comment]
Hi @tandrew,

I have released version 1.11.1 that should fix this.
Let me know if anything still doesn't behave as expected.

**Comment by tandrew** [comment]
Hi @antoniandre,
Looking good so far!

Thanks a bunch. I shall keep you posted if anything else turns up 👍

**Comment by antoniandre** [comment]
Hi @tandrew, if everything is still looking good I will close this issue!
We can reopen later if we find something is not right.

**Comment by tandrew** [comment]
Sure @antoniandre,
Thanks for this and will let you know if something else comes up.

**Comment by tandrew** [comment]
Hi @antoniandre,
I am still experiencing issues. While it is now reactive, I am getting a lot of jitter when dragging a separator.

Try dragging the horizontal separator in this [CodePen](https://codepen.io/tandrew-the-bold/pen/ZVXvMP?editors=1111) and you will see what I mean.

Maybe something I am doing wrong here?

![feb-07-2019 18-13-13](https://user-images.githubusercontent.com/8017453/52429467-696b1600-2b04-11e9-8bc0-10e237659f1c.gif)
