### ISSUE TITLE
Direction switching doesn't update the panes style

### ISSUE THREAD

**Issue by SebastienWae** [antoniandre/splitpanes#70]
### Environment
**Splitpanes Version:** 2.1.1
**Browsers:** Chrome 78.0.3904.108 & Firefox 71.0
**OS:** Windows 10

### Steps to reproduce
Switch splitpanes from vertical to horizontal or horizontal to vertical

### Expected Behavior
The planes should move in the new direction and conserve their relative sizes.

### Actual Behavior
The planes are moving in the new direction but the sizes are set back to default and the width/height are not switched resulting in a "broken" state.

### Reproduction Link
https://jsfiddle.net/7saw1ymd/3/

**Comment by SebastienWae** [comment]
Currently, my solution is to manually switch the height and width every time I switch direction.

https://jsfiddle.net/fk756sdv/

**Comment by antoniandre** [comment]
Hi @SebastienWae,

Indeed, this will be fixed in the next version. will let you know when ready

**Comment by antoniandre** [comment]
Hi @SebastienWae, This is now fixed in version 2.2.0.
https://antoniandre.github.io/splitpanes/#change-direction
