### ISSUE TITLE
Resize event when pane is added / removed programmatically

### ISSUE THREAD

**Issue by petersutter** [antoniandre/splitpanes#71]
When a pane is added or removed programmatically it would be nice if the resize (and/or resized) event is fired as the dimensions of the panes changes.

**Comment by antoniandre** [comment]
Hi @petersutter,
Indeed, the `resized` event will be fired after pane is added/removed in the next release, will let you know.

**Comment by antoniandre** [comment]
Hi @petersutter, 
This is now available from version 2.2.0.
I also added 2 new events called `pane-add` and `pane-remove` please check the release notes for the few improvements in this version!
https://antoniandre.github.io/splitpanes/#release-notes

Hope it helps.
