### ISSUE TITLE
Exclude core-js polyfill from package (?)

### ISSUE THREAD

**Issue by novrain** [antoniandre/splitpanes#72]
please reference this issue:
[No way to not include core-js polyfills for libraries](https://github.com/vuejs/vue-cli/issues/1919)

**Comment by antoniandre** [comment]
Hi @novrain,

I had a look at the output size after publishing a new patch to NPM here is the output, everything looks normal to me: 

```
npm publish        Tue 17 Dec 10:38:43 2019
npm notice 
npm notice 📦  splitpanes@2.1.2
npm notice === Tarball Contents === 
npm notice 1.1kB   LICENSE                       
npm notice 3.2kB   dist/splitpanes.css           
npm notice 192B    dist/demo.html                
npm notice 132.9kB dist/splitpanes.common.js     
npm notice 133.3kB dist/splitpanes.umd.js        
npm notice 42.4kB  dist/splitpanes.umd.min.js    
npm notice 1.7kB   package.json                  
npm notice 167.4kB dist/splitpanes.common.js.map 
npm notice 168.0kB dist/splitpanes.umd.js.map    
npm notice 195.0kB dist/splitpanes.umd.min.js.map
npm notice 2.4kB   README.md                     
npm notice === Tarball Details === 
npm notice name:          splitpanes                              
npm notice version:       2.1.2                                   
npm notice package size:  207.4 kB                                
npm notice unpacked size: 847.6 kB                                
npm notice shasum:        851dff0a492f9eff2aba06cbf050f3530bd71644
npm notice integrity:     sha512-IiVeC1wk7yVq4[...]eLTNEyDCKRXSQ==
npm notice total files:   11                                      
npm notice 
+ splitpanes@2.1.2
```

You can see the unpacked size is 847.6 kB, this is only the sum of the files listed above.
It does not mean that the production build of your app will include all that, you will only use the files `dist/splitpanes.common.js` and `dist/splitpanes.css` all the `.map` are for dev environment so that you can inspect the code, the package.json readme.md and license are useful for the package creation but never use from your end, and all the .umd files are there for the unpkg CDN.

In the end, the final weight in your app should be 132.9kB js + 3.2kB css

Also everything is gzipped in the end which reduces the file size a lot.

If you open the file `dist/splitpanes.common.js`, everything is already transpiled into backward compatible Javascript, which is normal and what we want. So that you can use this lib from CDN as is for instance.

Hope it helps.

**Comment by novrain** [comment]
hi @antoniandre 
If we exclude core-js, the size will be:

```
  File                          Size                   Gzipped

  dist\splitpanes.umd.min.js    13.06 KiB              4.19 KiB
  dist\splitpanes.umd.js        37.38 KiB              9.37 KiB
  dist\splitpanes.common.js     37.00 KiB              9.25 KiB
  dist\splitpanes.css           3.16 KiB               0.62 KiB

```
maybe you should just have a try, please.

In the bable.config.js

```
module.exports = {
    presets: [
        ['@vue/app', {
            useBuiltIns: false
        }]
    ]
}
```

npm pulish 

```
npm notice
npm notice package: splitpanes@2.1.2
npm notice === Tarball Contents ===
npm notice 1.1kB  LICENSE
npm notice 3.2kB  dist/splitpanes.css
npm notice 192B   dist/demo.html
npm notice 37.9kB dist/splitpanes.common.js
npm notice 38.3kB dist/splitpanes.umd.js
npm notice 13.4kB dist/splitpanes.umd.min.js
npm notice 1.9kB  package.json
npm notice 41.4kB dist/splitpanes.common.js.map
npm notice 41.9kB dist/splitpanes.umd.js.map
npm notice 47.1kB dist/splitpanes.umd.min.js.map
npm notice 2.4kB  README.md
npm notice === Tarball Details ===
npm notice name:          splitpanes
npm notice version:       2.1.2
npm notice package size:  59.9 kB
npm notice unpacked size: 228.7 kB
npm notice shasum:        a951227e95c5c8ee22b3a5baa6b8fb5bff2b1c9d
npm notice integrity:     sha512-6R0YIdcrKLntg[...]I8rYLoaMHaxfw==
npm notice total files:   11
npm notice
```

**Comment by antoniandre** [comment]
Hi @novrain, 
Thanks for the details, I tried it and it is indeed smaller in size and still transpiled, but what about IE10 support out of the box? I am not sure about it but can't test it as I don't have Windows.
By the way what is your use case? are you going to use this only on latest browsers or do you think of adding core-js yourself?

**Comment by novrain** [comment]
In vue cli3 project, the core-js is an default dependency in package.json
If echo componet lib such splitspane embed core-js again, it will be duplicate many times.

As for IE11,  if we run (even dose not exclude core-js)

`npm run serve`

then open splitspens in IE11, we will get this error:

`Object doesn't support property or method 'startswith'`

**Comment by antoniandre** [comment]
Indeed, the `Object doesn't support property or method 'startswith'` error comes from the lack of polyfill, which made me realise the polyfill was missing on the documentation page. Thanks for that.

Now that it is added it should not say it when you visit the documentation on IE 11.

Now if I exclude the polyfill from the package, all the users will have the same problem on IE and they will need a manual polyfill inclusion which is more troublesome.

I need to think it over and read some docs about it. 
So I am reopening this issue until I know what best to do. ;)

**Comment by novrain** [comment]
@antoniandre 
Thank you!

**Comment by antoniandre** [comment]
Hi @novrain,
It took me a while to make a decision, but here it is.
There are pros and cons and different opinions about it.

But base on what I read and my will to make this library easy to use, I decided to keep the polyfills in. At least for now.

According to: https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/babel-preset-app#usebuiltins, the default is to add only the polyfills that are needed based on the code transpiled by Babel. So exactly what is needed by Splitpanes, no more no less and automatically.

This represents 29kB on a total weight of 42kB unzipped. This difference is very minor especially with nowadays connectivity, and is a tradeoff that I take to facilitate the use of this library. It will support IE11 out of the box for a few extra kb, I consider it worth it.

Splitpanes has been announced as supporting IE 11, so I am not removing the support yet. I also think IE is outdated by now but some websites must still be compatible.

On another aspect, if I remove the polyfills and let the user do as wish it is not only inconvenient but also not optimized as they would have to use the `entry` value on the `usebuiltins` option - which includes ALL the polyfills - as they don't know which exact features of ES6 needing polyfills are used in the library. In the end it would be more kb waste. I also don't want to maintain a curated list of all the polyfills needed in Splitpanes at any time.

Hope it makes sense!
