### ISSUE TITLE
Applying default pane size on pane add/remove

### ISSUE THREAD

**Issue by amir20** [antoniandre/splitpanes#74]
I think I have found a bug when hiding panes programmatically on the mobile. 

I have something that looks like this:

```
<splitpanes>
  <pane v-if="!mobile" size="15">menu</pane>
  <pane size="85">main app</pane>
</splitpanes>
```

All works fine. When I resize to smaller width, the second pane takes 100%. However, if load the page while the width is small, then the second pane will be 85%. Even though, only one pane is shown. 

See screenshot of my dom below:
<img width="1263" alt="Screen Shot 2019-12-18 at 10 49 30 AM" src="https://user-images.githubusercontent.com/260667/71114181-15997680-2184-11ea-990c-6e8b41886f7a.png">

I noticed width for all panes is required. One possible solution would be to not make that required and just calculate the remaining width. 

A workaround would be to set width on second pane to 100% if `mobile==true` but that's hacky for sure.

**Comment by antoniandre** [comment]
Hi @amir20, 
Thanks for reporting, this is actually the same bug as #67, I am currently working on a fix for that.
Please continue the discussion in #67 if you need to, 
I will update in there when the fix is ready.

**Comment by antoniandre** [comment]
Should now be fixed (same as #67).

**Comment by amir20** [comment]
Hi @antoniandre I checked with latest v2.2.0 and it doesn't look to be fixed. See screenshot

<img width="612" alt="Screen Shot 2019-12-20 at 10 43 38 AM" src="https://user-images.githubusercontent.com/260667/71283739-e450b000-2315-11ea-94b3-1bc27c05e9ae.png">

**Comment by antoniandre** [comment]
Hi @amir20,

Sorry I misread the issue you reported, I did fix the fact that you can now toggle a pane with `v-if` and then resize it correctly, but I did not change the fact that if you have a default width you have to provide all of them.

So for now please do your workaround and I will allow setting only one default size and calculate the rest. I also need to check all the default sizes when adding a pane.

Will let you know when available.
Sorry for reading the issue too fast.

**Comment by amir20** [comment]
So is this fixed now because it's similar to $74?

**Comment by antoniandre** [comment]
Hi @amir20,

I released a patch to fix the fact that when adding a new pane it should be set to its defined size if any.
If no size is provided, it will resize the panes evenly.

You can check your updated demo: https://codepen.io/antoniandre/pen/vYEmJjq.
If you are happy with this behavior then you can close the issue.

I still have to rewrite some code but that  should not affect the behavior discussed here.

I am also working on the fact that all the sizes are needed as you mentioned. in the new release you should be able to provide only the size you need and the rest of the panes will receive the same amount of the remaining space. E.g. for 3 panes, pane 1 has size="10", pane 2 gets 45%, pane 3 gets 45%.

If ever I need to introduce new parameters as discussed in #76 I will let you know.

**Comment by amir20** [comment]
I'll try this weekend and let you know. Thanks!

**Comment by amir20** [comment]
I think it works! I tested it locally and will play with it more.
