### ISSUE TITLE
Panes always starts with size 50%

### ISSUE THREAD

**Issue by calebeaires** [antoniandre/splitpanes#76]
On page load, panes does not obey the size property. On the example below I use two panes with the respective sizes: 20 and 80. When loading page, the pane is adjusted. Take a look at the GIF below:

![insigh](https://user-images.githubusercontent.com/794195/72017106-cd7de900-3243-11ea-970d-c87dd4b53126.gif)

How to make the pane starts with the defined sizes?

**Comment by antoniandre** [comment]
Hi @calebeaires,
That's right, I refactored the library and then forgot to re-apply assigned sizes on load. 
I'll get this fixed as soon as I have some time.

**Comment by calebeaires** [comment]
Thanks to that. Hope on you. My project is entirely build on splitpanes.

**Comment by antoniandre** [comment]
@calebeaires, 
I just checked the initial load behavior and it's fine, so it must be after toggling or adding a pane dynamically like in this Codepen: https://codepen.io/antoniandre/pen/vYEmJjq
(Initial load is fine but after toggle it's back to 50%)

So this is the same issue as #74.

I'll have a look later today, will let you know when fixed.

**Comment by antoniandre** [comment]
Hi @calebeaires, I released a hot fix that should solve your problem.
For that make sure you use the patch 2.2.1

I had to release an incomplete solution as this will require a lot more work.
I have started the refactoring in a branch but there are multiple scenarios of what the user may want when adding or deleting a pane, it could be: 
- resize equally all the panes
- increase or decrease the next pane accordingly

 I will probably need to introduce new parameters to allow different outcomes.

**Comment by calebeaires** [comment]
I have updated, tested too. Still with the same issue. I will wait to the next release. Thanks.

**Comment by antoniandre** [comment]
Hi @calebeaires, 
I will need your code to know what to fix then if your problem is different than the Codepen demo.
Please fork this Codepen and put your code.
Thanks.

**Comment by calebeaires** [comment]
Here you have. No v-ifs, no v-shows. Splitpanes is loaded as the vue render its page. Content inside the panes is from the server. This content appears after some time (2 or 3 seconds).

```vue
<template>
    <splitpanes class="default-theme splitpanes-border">
        <pane :size="25" class="split-inner">
              <div>
                    <!-- div and divs -->
              </div>
        </pane>
        <pane :size="75" class="split-inner">
              <!-- div and divs -->
        </pane>
    </splitpanes>
</template>

<style lang="scss">
// splitplane styles changes
.splitpanes.default-theme.splitpanes-border {
  .splitpanes__pane {
    background-color: #ffffff;
    border: 2px solid #888;
    overflow: hidden;
    background: #fff;
    // margin-right: 1px;
    // margin-left: 1px;
    .splitpanes--vertical {
      box-shadow: 1px 1px 1px #444;
    }
  }
  .splitpanes--vertical > .splitpanes__splitter,
  .splitpanes--vertical > .splitpanes__splitter {
    width: 10px !important;
    border-left: 0px solid #eee !important;
    margin-left: 0px !important;
  }
  .splitpanes__splitter {
    background-color: transparent;
  }
  .splitpanes__splitter:after,
  .splitpanes__splitter:before {
    background-color: #888;
  }

  .splitpanes--vertical > .splitpanes__splitter,
  .splitpanes--vertical > .splitpanes__splitter {
    // margin-left: 0px;
  }
}

.default-theme.splitpanes--vertical>.splitpanes__splitter, .default-theme .splitpanes--vertical>.splitpanes__splitter {
  width: 10px !important;
  border-left: 0px solid #eee !important;
  margin-left: 0px !important;
}
  .splitpanes.default-theme.splitpanes-border .splitpanes__pane {
    background-color: transparent;
    border: none;
    overflow: hidden;
    background: transparent;
  }
</style>
```

**Comment by antoniandre** [comment]
Hi @calebeaires,

I have put the code you gave me in a codepen: https://codepen.io/antoniandre/pen/bGNQpqG.
Loading the default sizes works as expected.

I'm sorry to say that but your CSS is very messy, redundant, and causes problems, you should clean it up.

If you want to redo the splitpanes styles yourself which is fine, follow this example: https://antoniandre.github.io/splitpanes/#do-your-own-style

Hope it helps.

**Comment by Orayi** [comment]
Not sure if this is any help.

I've managed to get the same issue as the OP when using splitpane with bootstrap-vue. 

If splitpane is the only component on the page everything works as expected. As soon as I put the navbar component before it the panes start at 50% then resize.

I've created an example in codepen: https://codepen.io/orayi/pen/oNgVqEM

**Comment by calebeaires** [comment]
@Orayi  Same here!

**Comment by antoniandre** [comment]
Hi @Orayi, @calebeaires,

Thanks for taking the time to create a Codepen @Orayi.
I still don't see any problem here though: 
- There is a transition on the pane component, so when there is no other component it loads faster and when it mounts it's applied the size you give it and you don't see the transition as it applies fast enough to be added in the DOM with the updated styles.
- When there is another component that also has some execution time on mounted, the Panes are added to the DOM but the styles are not applied fast enough (next tick) and you see the transition.

But in both cases, the sizes of the panes are applied correctly.

If you disable the transition, you will probably not have time to see the resizing happen: `.splitpanes .splitpanes__pane {transition: none;}`

Hope it makes sense, let me know if there is still an issue where the size is not applied.

**Comment by Orayi** [comment]
@antoniandre removing the transition works perfectly, thanks

**Comment by calebeaires** [comment]
it works now. thanks
