### ISSUE TITLE
@resize must emit event immediate

### ISSUE THREAD

**Issue by Bellski** [antoniandre/splitpanes#8]
Now resize event emits after drag's end.

**Comment by antoniandre** [comment]
That's intended from the beginning and discussed here https://github.com/antoniandre/splitpanes/issues/4. 
There is no benefit in emitting an event foreach pixel you resize IMO.

Did you have a good reason for that?

**Comment by Bellski** [comment]
Sure, for example i need to update size of child component, when drag gutter. Now child will resize after drag's end, looks not good. U can make immediate postfix, `@resize.immediate`

**Comment by antoniandre** [comment]
Can't you set your component size in percentage so it does not need any calculation?

**Comment by Bellski** [comment]
I'm using monaco editor, when container resizing i must call update method to recalculate size of editor. To make smooth resizing, that's why i need this, this is pretty default thing for split panes. But i don't mind, i just moved resize event in to  `onMouseMove`

**Comment by antoniandre** [comment]
Hi @Bellski,

Splitpanes now emits an event on resize and another event on resize end.
Also note that watching slots is now an option that you should activate to keep full reactivity (https://antoniandre.github.io/splitpanes/#in-depth-reactivity).

Please check the release notes: https://antoniandre.github.io/splitpanes/#release-notes

Hope it solves the issue!

**Comment by Bellski** [comment]
Nice, but i can't understand who need non-reactive components? And why splipanes affects on child component reactivity ?

**Comment by antoniandre** [comment]
Remaining problem in this issue is related to #14, please follow up in there.
