### ISSUE TITLE
The latest version of the component does not provide a TS declaration

### ISSUE THREAD

**Issue by ldcmd** [antoniandre/splitpanes#82]
![1](https://user-images.githubusercontent.com/25797957/74803145-d7047180-5316-11ea-8811-3d7f7a8d97b2.png)
![2](https://user-images.githubusercontent.com/25797957/74803146-d966cb80-5316-11ea-810f-04d1a1e3f055.png)
![3](https://user-images.githubusercontent.com/25797957/74803149-db308f00-5316-11ea-843b-0f207ffc9d67.png)

**Comment by Rohit-nagbhidkar** [comment]
Facing the same issue 
not having any TS declaration for new version

**Comment by antoniandre** [comment]
Hi guys,
I have not added or removed any TS declaration, but if you know what's missing to declare I am happy to merge that in or paste it in the codebase.
I don't use Typescript so you will probably know better.

**Comment by hnviradiya** [comment]
after upgrading to latest (from 1.14.2 to 2.2.1). I am facing "Unknown custom element: <splitpanes> - did you register the component correctly? For recursive components, make sure to provide the "name" option."

**Comment by devendra-kumar1** [comment]
@antoniandre : Do you have typescript support for this project ? Please confirm ASAP

**Comment by N0K0** [comment]
Had the same issue, resolved it by adding
`"@types/splitpanes": "^1.0.0",` to my package.json

I'm rather new to JS, would it suffice to update your package.json with that dependency?

**Comment by moltar** [comment]
FYI

`@types/splitpanes` only has definitions for `splitpanes@1`.

There's an open PR by @N0K0 to update it: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47156

**Comment by antoniandre** [comment]
Thanks for this information @moltar.
As I am not using typescript, I haven't added any type definition, but if anyone wants to submit a PR with the type definitions I am happy to add it in the codebase!

**Comment by N0K0** [comment]
@antoniandre cool!
I'm not using TS myself per sé. Web Storm just need some sort of source to figure out its auto complete from what i understand. But then again! Relatively new to anything frontend 😅

**Comment by moltar** [comment]
@N0K0 it'd probably be less troublesome to add types to the project directly, than to the DT repo.

**Comment by andrewbranch** [comment]
> it'd probably be less troublesome to add types to the project directly, than to the DT repo

As a DT maintainer, I beg to differ 😄 

If anyone familiar with TypeScript and v2 of this library would like to review @N0K0’s DefinitelyTyped PR (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47156), that would help move it along! Since I’m not familiar with this library I can only spot-check it for common mistakes.

**Comment by jakenuts** [comment]
Here's a minimalist filler for this : splitpanes.d.ts

```
declare module 'splitpanes' {   
    export declare class Splitpanes extends Vue {}
    export declare class Pane extends Vue {}
}
```

**Comment by antoniandre** [comment]
Thanks @jakenuts for sharing. 

A quick question while I take advantage of your knowledge about TS: should this declaration just be added at the root of the component in https://github.com/antoniandre/splitpanes/blob/master/src/components/splitpanes/index.js?

**Comment by muhammeddemir** [comment]
@antoniandre I added as **splitpanes.d.ts** but it was not working. 
I changed to **index.d.ts** now it's working for typescripts.

Example:
![index](https://user-images.githubusercontent.com/23164910/101281772-23f00080-37e2-11eb-920a-c204474698bc.jpg)

```
declare module 'splitpanes' {   
    export declare class Splitpanes extends Vue {}
    export declare class Pane extends Vue {}
}
```

**Comment by andrewbranch** [comment]
For those not keeping track, the official typings are literally one character from being approved: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47156#discussion_r535657162

**Comment by andrewbranch** [comment]
It’s merged! Thanks @N0K0 for your hard work. Within a few minutes you’ll be able to `npm install -D @types/splitpanes`, and I would think this issue can be closed.

**Comment by antoniandre** [comment]
Awesome @N0K0 🙌 
Closing this issue then!
