### ISSUE TITLE
IE Issue Object does not support property remove.

### ISSUE THREAD

**Issue by JSulzberger** [antoniandre/splitpanes#83]
When move away from a page I get the error above.
![Capture](https://user-images.githubusercontent.com/45376030/75084001-0d7cff00-5558-11ea-95d7-b5f1d288a4fb.JPG)

**Comment by antoniandre** [comment]
Hi @JSulzberger,

If not solved please provide some code and reproduction link if you can.

**Comment by antoniandre** [comment]
Hi @JSulzberger, I have released a fix for removing the DOM nodes on IE11.
Please let me know if you still see an error.
