### ISSUE TITLE
pane-click event not firing

### ISSUE THREAD

**Issue by nmearl** [antoniandre/splitpanes#86]
The example webpage demonstrates setting and triggering various events, but the `pane-click` event does not appear to work. Likewise, in my own application, I can print to log with `@splitter-click="console.log($event)"`, but if I use `@pane-click="console.log($event)"` nothing happens.

**Comment by antoniandre** [comment]
Hi @nmearl, thanks for reporting, sorry I fix this much later.
This is now firing again in version 2.3.1
Hope it helps.

Closing the issue now, please reopen if not solved.
