### ISSUE TITLE
Splitpane slider behaves wrong with RTL pages

### ISSUE THREAD

**Issue by rostamiani** [antoniandre/splitpanes#89]
When _"body{direction:RTL}"_, the slider behaves wrong.
You can see the problem here. Just move the sliders:

https://codepen.io/rostamiani/pen/xxwEBvj

**Comment by eZawer** [comment]
All needed to work in rtl is to change one line in the following function:

    getCurrentDragPercentage (drag) {
      drag = drag[this.horizontal ? 'y' : 'x'] 
      // In the code bellow 'size' refers to 'width' for vertical and 'height' for horizontal layout.
      const containerSize = this.container[this.horizontal ? 'clientHeight' : 'clientWidth']
      if (!this.horizontal) {
       // *****************Reverse direction if rtl *************************************
        return document.body.dir=='ltr' ? drag * 100 / containerSize :  (containerSize-drag) * 100 / containerSize
      } else {
        return drag * 100 / containerSize
      }
    },

**Comment by rostamiani** [comment]
Can you make a pull request for this?

**Comment by antoniandre** [comment]
Hi @rostamiani, @eZawer,
This is now an option in splitpanes version 2.3.0: https://antoniandre.github.io/splitpanes/#api

Thanks @eZawer for pointing out what to change! ;)

**Comment by Tal500** [comment]
Hello and sorry for poping

> Hi @rostamiani, @eZawer, This is now an option in splitpanes version 2.3.0: https://antoniandre.github.io/splitpanes/#api
> 
> Thanks @eZawer for pointing out what to change! ;)

OK, I have moved the discussion for this feature to the original author [in this following issue](https://github.com/antoniandre/splitpanes/issues/167).
