### ISSUE TITLE
Feature request: max width / height

### ISSUE THREAD

**Issue by Alecyrus** [antoniandre/splitpanes#9]
See this: [link](https://codepen.io/alecyrus/pen/gZeBZg)
If you set the _splitpanes-max_ property like _splitpanes-min_ and try expanding the element which has red background, something strange will happen. The expanding dragging action will affect left panes...I have not checked the source code yet. Anyone help?

**Comment by Alecyrus** [comment]
@antoniandre

**Comment by antoniandre** [comment]
Hi @Alecyrus, 

Thanks for your interest, sorry but the max feature is not developed yet as written in the release notes.
It's next in my list!

**Comment by antoniandre** [comment]
Hi @Alecyrus,

The max feature is now released! Check the https://antoniandre.github.io/splitpanes/#horizontal-layout example.
Cheers.

**Comment by Alecyrus** [comment]
Awesome!  Good job 😃
