### ISSUE TITLE
改变数据顺序，拖动错乱

### ISSUE THREAD

**Issue by StriveTo** [antoniandre/splitpanes#92]
例：
  初始数据为[1, 2, 3] ,通过触发一个方法，将数据改为[1,3,2],会显示错乱
更改前：
![image](https://user-images.githubusercontent.com/34495324/84252390-19112780-ab41-11ea-8ce6-157fec5c8850.png)
更改后：
![image](https://user-images.githubusercontent.com/34495324/84252456-2dedbb00-ab41-11ea-914c-c7237c526002.png)

**Comment by antoniandre** [comment]
Please reopen in english if not solved.
