### ISSUE TITLE
When pane size is forced to 0 it doesn't seem to be recognized

### ISSUE THREAD

**Issue by jasonford** [antoniandre/splitpanes#94]
Setting to 0.00001 is my current working hack.

It's nice to set to 0 instead of just removing the pane since animation is much nicer for "hide" type behavior (especially for panels on the left).

I want to avoid using v-if="false" so avoid a re-mount for my in-pane components.

Thanks for the wonderful software!

**Comment by antoniandre** [comment]
Thanks for your feedback @jasonford.
It is now possible to set a size of `0` in version 2.2.2.
Please reopen if not solved.
Cheers.
