### ISSUE TITLE
Release ESM format lib and Vue3 support

### ISSUE THREAD

**Issue by amir20** [antoniandre/splitpanes#97]
Hi there, 

I have been recently using [vite](https://github.com/vitejs/vite) to do my development. It requires all modules to be in ESM format because vite uses ESM in the browser instead of a bundler. 

I noticed there is umd and common, but not ESM. 

Can you export ESM format too? Or at the very lease also include the `src/` folder when releasing so that we can use `import {...} 'src/components/'`.

**Comment by amir20** [comment]
Actually, sounds like I'll need more Vue3 support 

```
splitpanes.vue:658 Uncaught TypeError: h is not a function
    at Proxy.render (splitpanes.vue:658)
    at renderComponentRoot (vue.js:1543)
    at componentEffect (vue.js:5152)
    at reactiveEffect (vue.js:330)
    at effect (vue.js:305)
    at setupRenderEffect (vue.js:5144)
    at mountComponent (vue.js:5102)
    at processComponent (vue.js:5058)
    at patch (vue.js:4708)
    at mountChildren (vue.js:4871)

```

**Comment by amir20** [comment]
Any update on this? I have tried getting it to work with Vue3 but was unable to get it working after a couple of hours of debugging.

**Comment by antoniandre** [comment]
Hi @amir20, I'll be starting the migration to Vue 3 shortly, it will not work without some refactoring.

Also IMHO, Vue 3 is still a little bit fragile atm, looking at some critical open issues and PRs.
Even if I love Vue and Vue 3 even more, I wouldn't rush into it.

**Comment by antoniandre** [comment]
Hi @amir20,
Vue 3 is now supported! 🎉 
https://antoniandre.github.io/splitpanes/#installation

**Comment by antoniandre** [comment]
Hi @amir20, sorry to say that but Webpack is not yet capable of exporting to ESM (so vue-cli neither).
The good news is it's in the pipe and will be a feature of Webpack 5!
https://github.com/webpack/webpack/issues/2933

For now you can probably find a tool to convert it to ESM one-shot.
Hope this helps.

I am closing this issue as Vue 3 is now supported and there is no way to build an ES module using vue-cli at the moment.

**Comment by amir20** [comment]
Can you just include the src dir when publishing the npm package? ESM is just the original code in this case. 

Vue3 is pushing for vitejs which uses roll up in prod. 


Sent via my iPhone

**Comment by antoniandre** [comment]
Sure I can include the source code, will push it later today, you will see a commit reference to this thread.
I used to build Splitpanes with Rollup at the beginning, I have to say I much prefer vue-cli, it's a breeze.
Cheers.

**Comment by amir20** [comment]
I also favor webpack. Haven’t used vue-cli much though. But recently I started looking at other solutions because my development experience was slow with webpack. 

Thanks for your support. I’ll update you when I try it again.
