### ISSUE TITLE
non-passive event listener in Chrome warning

### ISSUE THREAD

**Issue by huzjakd** [antoniandre/splitpanes#98]
I'm trying it in Chrome iPad emulator and I get this warning:

Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.

**Comment by antoniandre** [comment]
Hi @huzjakd,
thanks for reporting. Pease disregard this warning as the passive parameter is explicitly set to false to prevent scrolling while dragging on touch devices.

Here is the implementation:

```js
    bindEvents () {
      document.addEventListener('mousemove', this.onMouseMove, { passive: false })
      document.addEventListener('mouseup', this.onMouseUp)

      // Passive: false to prevent scrolling while touch dragging.
      if ('ontouchstart' in window) {
        document.addEventListener('touchmove', this.onMouseMove, { passive: false })
        document.addEventListener('touchend', this.onMouseUp)
      }
    }
```

Let me know if you need further information or help.
